### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by dansiegel** [dessant/lock-threads#16]
Is there a way we can update the batch size... we have so many issues that it's quite annoying getting batches of 30 coming in all day long... it would really be helpful to up that limit and get it over and done with.

**Comment by dessant** [comment]
GitHub has API limits and the app instance handles tens of thousands of repositories, so locking must be sheduled in small batches.

You could deploy your own instance and modify the source to increase the batch size.

Adding a config option for the batch size could also be useful for those who self host.

**Comment by dansiegel** [comment]
isn't the API limit usually 100? it would be great if this were an option on the YAML that you could configure

**Comment by dessant** [comment]
Rate limits depend on the API endpoint and the popularity of the app: https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/

> It would be great if this were an option on the YAML that you could configure

I agree that such an option would be great for this app, but it could only be respected when you self-host the instance, because of the API limits.

If you're not in a hurry, I plan to release this app as a GitHub Action in about 2 weeks, that would not need to be self-hosted, actions can be added to repositories as config files and they are interpreted on GitHub servers, so they wouldn't be bound to the rate limits of a central app instance.

**Comment by dessant** [comment]
This project is now using GitHub Actions. You can temporarily increase the processing speed using workflow scheduling. Check the README for the available options and example workflow files.

The legacy GitHub app was moved [here](https://github.com/dessant/lock-threads-app).
